[package]
name = "change_coin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["dp"] # change this to change the part logic
naive = []
dp = []

[dependencies]
rstest = "0.18.2"
